# Generated by Django 3.2.3 on 2021-06-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.log')),
            ],
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
