# Generated by Django 3.2.3 on 2021-06-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20210601_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solution',
            new_name='Solutions',
        ),
    ]
