# Generated by Django 3.2.3 on 2021-06-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_alter_log_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
