# Generated by Django 3.2.3 on 2021-06-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_alter_log_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=500)),
        ),
    ]
