# Generated by Django 3.2.3 on 2021-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_log_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_by',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
