# Generated by Django 3.2.3 on 2021-06-02 10:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_alter_log_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
