# Generated by Django 3.2.3 on 2021-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_alter_log_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='slug',
            field=models.SlugField(),
        ),
    ]
