# Generated by Django 3.2.3 on 2021-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_alter_log_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_by',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
