# Generated by Django 3.2.3 on 2021-06-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='likes',
        ),
    ]
