# Generated by Django 3.2.3 on 2021-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0025_alter_comments_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
