# Generated by Django 3.2.3 on 2021-06-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0026_log_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='image',
            new_name='avatar',
        ),
    ]
