# Generated by Django 3.2.3 on 2021-06-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0027_rename_image_log_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.solutions'),
        ),
    ]
