# Generated by Django 3.2.3 on 2021-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0028_alter_comments_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
