# Generated by Django 3.2.3 on 2021-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0029_solutions_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='created_by',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
