# Generated by Django 3.2.3 on 2021-06-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0030_solutions_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='created_by',
        ),
    ]
