# Generated by Django 3.2.3 on 2021-06-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0031_remove_solutions_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='log',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='log.log'),
        ),
    ]
