# Generated by Django 3.2.3 on 2021-06-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0032_alter_solutions_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.log'),
        ),
    ]
