# Generated by Django 3.2.3 on 2021-06-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0034_solutions_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='avatar',
            new_name='image',
        ),
    ]
