# Generated by Django 3.2.3 on 2021-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0036_auto_20210610_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
